{% set name = "dbus-fast" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbus_fast-{{ version }}.tar.gz
  sha256: ab36d7bf4a8dfea94b9c227b1dd10f33996e2e69458f492738852ca8f5d5ff27

build:
  script_env:
    - REQUIRE_CYTHON=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    - /lib64/libc.so.6  # [linux]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython >=3,<3.1.0                     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=65.4.1
    - cython >=3,<3.1.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python

test:
  imports:
    - dbus_fast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluetooth-devices/dbus-fast
  summary: A faster version of dbus-next
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
