{% set name = "dbus-fast" %}
{% set version = "2.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbus_fast-{{ version }}.tar.gz
  sha256: dbb7daa73ace224037c0b478e9d9519a721f99995eb53745862fa13ed9db13df

build:
  script_env:
    - REQUIRE_CYTHON=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    - /lib64/libc.so.6  # [linux]

requirements:
  host:
    - {{ compiler('c') }}
    - python
    - setuptools >=65.4.1
    - cython >=3,<3.1.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python

test:
  imports:
    - dbus_fast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluetooth-devices/dbus-fast
  summary: A faster version of dbus-next
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
