{% set name = "dbus-fast" %}
{% set version = "1.87.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbus_fast-{{ version }}.tar.gz
  sha256: ef23adb1f1e5367b84351839aef3ba28afb7156ac02d5ba1c4048b60a8fa4993

build:
  script_env:
    - REQUIRE_CYTHON=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    - /lib64/libc.so.6  # [linux]

requirements:
  host:
    - {{ compiler('c') }}
    - python
    - setuptools >=65.4.1
    - cython
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - async-timeout >=3.0.0

test:
  imports:
    - dbus_fast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluetooth-devices/dbus-fast
  summary: A faster version of dbus-next
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
